@startuml
'https://plantuml.com/class-diagram
    !theme sandstone
    abstract class NetworkTopology
    interface CriticalPath
    interface ServiceChain{
        object: orthogonalList
    }
    interface ServicePlacementAlgorithm
    interface ServiceScalingAlgorithm
    class Service{
        ArrayList: replicas
        object: serviceCharacteristics
    }
    class ServiceCharacteristics
    class Replica{
        int: resource share
    }
    class ServiceCloudlet{
        int: length
        int: bw
        int: ram
        int: mips
        object: utilizationModel
    }
    class ServiceCloudletScheduler

    ServiceChain o--> CriticalPath
    note on link: Topological Sorting
    CriticalPath *-- Service

    Service <|-- ServiceCharacteristics
    Service <|-- Replica
    Service -- ServiceCloudlet

'    ServicePlacementAlgorithm -- Service
    ServicePlacementAlgorithm .. Replica
    ServiceScalingAlgorithm .. Service

    ServiceCloudlet ..> ServiceCloudletScheduler
'    ServiceCloudlet .. NetworkTopology
    ServiceCloudlet <.. CriticalPath


@enduml

